#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands( array(
	new \Marowak\Commands\Phpstorm\Scopes\Sync(),
	new \Marowak\Commands\LocalWp\Setup\WP_Cli(),
	new \Marowak\Commands\Phpstorm\WordPress(),
) );

$application->run();
